# Generated by Django 6.0.4 on 2026-04-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="discord_id",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
