# Generated by Django 6.0.4 on 2026-05-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discord_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordchannel",
            name="cleanup_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="discordchannel",
            name="last_cleanup_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
