"""Add Bedmages

Revision ID: 027e1422f89b
Revises: 
Create Date: 2025-05-27 15:06:34.143694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '027e1422f89b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bedmages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['character_name'], ['characters.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bedmages_character_name'), 'bedmages', ['character_name'], unique=False)
    op.create_index(op.f('ix_bedmages_id'), 'bedmages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bedmages_id'), table_name='bedmages')
    op.drop_index(op.f('ix_bedmages_character_name'), table_name='bedmages')
    op.drop_table('bedmages')
    # ### end Alembic commands ###
