"""Added ne table bedmages

Revision ID: 8626a97096f1
Revises: ab4ae06c9a62
Create Date: 2025-05-26 16:23:38.521640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8626a97096f1'
down_revision: Union[str, None] = 'ab4ae06c9a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bedmage_monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_name'], ['characters.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bedmage_monitors_character_name'), 'bedmage_monitors', ['character_name'], unique=False)
    op.create_index(op.f('ix_bedmage_monitors_id'), 'bedmage_monitors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bedmage_monitors_id'), table_name='bedmage_monitors')
    op.drop_index(op.f('ix_bedmage_monitors_character_name'), table_name='bedmage_monitors')
    op.drop_table('bedmage_monitors')
    # ### end Alembic commands ###
