# Generated by Django 6.0.4 on 2026-04-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("sex", models.CharField(blank=True, default="", max_length=16)),
                ("vocation", models.CharField(blank=True, default="", max_length=32)),
                ("level", models.PositiveIntegerField(blank=True, null=True)),
                ("world", models.CharField(blank=True, default="", max_length=32)),
                ("residence", models.CharField(blank=True, default="", max_length=64)),
                ("house", models.CharField(blank=True, default="", max_length=128)),
                (
                    "guild_membership",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "last_login",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "account_status",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("last_scraped_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-level"],
                "indexes": [
                    models.Index(fields=["name"], name="characters__name_6d8b81_idx")
                ],
            },
        ),
    ]
