# Generated by Django 6.0.4 on 2026-04-24 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="character",
            name="characters__name_6d8b81_idx",
        ),
    ]
