# Generated by Django 6.0.4 on 2026-05-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0003_seed_default_periodic_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="guild_membership",
            field=models.CharField(blank=True, default="", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="house",
            field=models.CharField(blank=True, default="", max_length=128, null=True),
        ),
    ]
