# Generated by Django 6.0.4 on 2026-05-16 18:45

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0005_dedupe_character_names"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="character",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="character_name_lower_unique",
            ),
        ),
    ]
