# Generated by Django 6.0.4 on 2026-05-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("characters", "0006_character_name_lower_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="last_deaths_scraped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
