# Generated by Django 6.0.4 on 2026-05-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeathEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_name", models.CharField(db_index=True, max_length=64)),
                ("level_at_death", models.PositiveIntegerField()),
                ("killed_by", models.TextField(blank=True, default="")),
                ("died_at", models.DateTimeField(db_index=True)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-died_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character_name", "died_at"),
                        name="unique_death_event_per_character_time",
                    )
                ],
            },
        ),
    ]
