# Generated by Django 6.0.4 on 2026-05-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deaths", "0002_seed_periodic_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="deathevent",
            name="announced_on_discord",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
