# Generated by Django 6.0.4 on 2026-05-17 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("characters", "0007_character_last_deaths_scraped_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeathWatchChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.BigIntegerField()),
                ("channel_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("guild_id",), name="deathwatch_channel_one_per_guild"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeathWatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="death_watches",
                        to="characters.character",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="death_watches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "character"),
                        name="unique_death_watch_per_user_character",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WatchedDeathEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_at_death", models.PositiveIntegerField()),
                ("killed_by", models.TextField(blank=True, default="")),
                ("died_at", models.DateTimeField(db_index=True)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announced_on_discord",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_deaths",
                        to="characters.character",
                    ),
                ),
            ],
            options={
                "ordering": ["-died_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character", "died_at"),
                        name="unique_watched_death_per_character_time",
                    )
                ],
            },
        ),
    ]
